# Generated by Django 3.0.4 on 2020-03-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumfile',
            name='image',
            field=models.FileField(upload_to='album/<function user_directory_path at 0x7fc2339117b8>'),
        ),
    ]
