# Generated by Django 3.0.4 on 2020-03-24 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file_upload_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_upload_app', '0002_auto_20200324_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumfile',
            name='image',
            field=models.FileField(upload_to=file_upload_app.models.user_directory_path),
        ),
        migrations.CreateModel(
            name='AvatarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=file_upload_app.models.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
